#ifndef CAN_IDS_H
#define CAN_IDS_H

enum can_ids {
    CAN_ID_IS_EMERGENCY,
    CAN_ID_IS_EMERGENCY_BUTTON_PRESSED,
    CAN_ID_IS_EMERGENCY_SWITCH_TOGGLED,
    CAN_ID_IS_HYDROGEN_LEAKING,
    CAN_ID_IS_SC_RELAY_CLOSED,
    CAN_ID_IS_TIME_RESET_BUTTON_PRESSED,
    CAN_ID_IS_HALF_SPEED_BUTTON_PRESSED,
    CAN_ID_IS_GAS_BUTTON_PRESSED,
    CAN_ID_FUEL_CELL_MODE,

    CAN_ID_FC_CURRENT,
    CAN_ID_FC_SC_CURRENT,
    CAN_ID_SC_MOTOR_CURRENT,
    CAN_ID_FC_VOLTAGE,
    CAN_ID_SC_VOLTAGE,
    CAN_ID_HYDROGEN_SENSOR_VOLTAGE,
    CAN_ID_FUEL_CELL_TEMPERATURE,
    CAN_ID_FAN_RPM,
    CAN_ID_VEHICLE_SPEED,
    CAN_ID_MOTOR_PWM,
    CAN_ID_HYDROGEN_PRESSURE,

    CAN_ID_GPS_LATITUDE,
    CAN_ID_GPS_LONGITUDE,
    CAN_ID_GPS_ALTITUDE,
    CAN_ID_GPS_SPEED,

    CAN_ID_MOTOR_SPEED,
    CAN_ID_MOTOR_CURRENT,
    CAN_ID_FC_CURRENT_RAW,
    CAN_ID_FC_VOLTAGE_RAW,
    CAN_ID_MC_CURRENT,

    CAN_ID_LAP_NUMBER
};

#endif